name: CI/CD Pipeline mit E2E-Tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  e2e-validation:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Code-Checkout
        uses: actions/checkout@v4
      - name: Node.js Umgebung initialisieren
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Abhängigkeiten installieren
        run: npm ci
      - name: Playwright Browser-Binaries installieren
        run: npx playwright install --with-deps
      - name: End-to-End Tests ausführen
        run: npm run test:e2e

      # Debugging i Artefaktit Fillim: Vetëm ato që nuk dështojnë
      - name: Debug: Check current working directory and list files
        run: |
          pwd # Printon direktorinë aktuale të punës
          ls -la # Liston të gjithë skedarët dhe folderat në direktorinë aktuale

      - name: Testbericht als Artefakt speichern
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
