name: CI/CD Pipeline mit E2E-Tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  e2e-validation:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Code-Checkout
        uses: actions/checkout@v4
      - name: Node.js Umgebung initialisieren
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Abhängigkeiten installieren
        run: npm ci
      - name: Playwright Browser-Binaries installieren
        run: npx playwright install --with-deps
      - name: End-to-End Tests ausführen
        run: npm run test:e2e

      # Debugging i Artefaktit FILLON KËTU
      - name: Debug: Check if playwright-report directory exists
        run: ls -la playwright-report/ # Do të listojë përmbajtjen e folderit

      - name: Debug: Check current working directory
        run: pwd # Do të printojë direktorinë aktuale të punës

      - name: Debug: List all files in current directory
        run: ls -la # Do të listojë të gjithë skedarët dhe folderat në direktorinë aktuale

      - name: Testbericht als Artefakt speichern
        if: always()
        uses: actions/upload-artifact@v4
        with: # <---- KUJDES: KY WITH DUHET TË KETË 2 HAPESIRA MË THJESHTË SE 'uses'
          name: playwright-report # <---- Kjo dhe 'path' duhet të jenë 2 hapsira më thellë se 'with'
          path: playwright-report/