name: CI/CD Pipeline mit E2E-Tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  # JOB 1: QUALITÄTSSICHERUNG (CI) FÜR PULL REQUESTS
  e2e-validation:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Printo emrin e repository-t
        run: echo "Repo: ${{ github.repository }}"
      - name: Code-Checkout
        uses: actions/checkout@v4
      - name: Node.js Umgebung initialisieren
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Abhängigkeiten installieren
        run: npm ci
      - name: Playwright Browser-Binaries installieren
        run: npx playwright install --with-deps
      - name: End-to-End Tests ausführen
        run: npm run test:e2e
      - name: Testbericht als Artefakt speichern
        if: always() # WICHTIG: Speichert den Bericht auch, wenn Tests fehlschlagen
        uses: actions/upload-artifact@v4
        with:
        name: playwright-report 
        path: playwright-report/
      - name: Testergebnisse als Artefakt speichern
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

  # JOB 2: AUSLIEFERUNG (CD) NACH ERFOLGREICHEM MERGE
  build-and-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Printo emrin e repository-t
        run: echo "Repo: ${{ github.repository }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Registry Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Docker Buildx initialisieren
        uses: docker/setup-buildx-action@v3
      - name: Docker-Image erstellen und veröffentlichen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_USER }}/playwright-test-project:latest
          platforms: linux/amd64,linux/arm64
