e2e-validation:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Code-Checkout
        uses: actions/checkout@v4
      - name: Node.js Umgebung initialisieren
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Abhängigkeiten installieren
        run: npm ci
      - name: Playwright Browser-Binaries installieren
        run: npx playwright install --with-deps
      - name: End-to-End Tests ausführen
        run: npm run test:e2e

      # Debugging Artefakt: Kontrollo direktorine aktuale dhe liston skedaret
      # Ky eshte hapi i diagnostikimit, s'ka lidhje me gabimin e sintakses ne linjen 29.
      - name: Debug: Check current working directory and list files
        run: |
          pwd
          ls -la

      # Ky eshte blloku ku ndodhet gabimi sintaksor ne linjen 29 (path: playwright-report/)
      - name: Testbericht als Artefakt speichern
        if: always()
        uses: actions/upload-artifact@v4
        # Aty poshte eshte linja 29: 'path: playwright-report/'
        with: # <-------------------- KY 'with' DUHET TE KETE KËTO HAPSIRA
          name: playwright-report
          path: playwright-report/
