name: CI/CD Pipeline mit E2E-Tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  e2e-validation:
    if: github.event_name == 'pull_request'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      
      # DEBUGGING: Check Playwright config
      - name: Debug - Check Playwright configuration
        run: |
          echo "=== Playwright configuration check ==="
          if [ -f "playwright.config.js" ]; then
            echo "✅ playwright.config.js exists"
            cat playwright.config.js
          else
            echo "❌ playwright.config.js missing"
          fi
          echo "=== Test directory check ==="
          ls -la tests/

      # RUN TESTS with explicit reporter flag  
      - name: Run Playwright tests (with explicit HTML reporter)
        run: |
          echo "=== Running Playwright tests ==="
          npx playwright test --reporter=html
          echo "=== Test execution completed ==="
      
      # COMPREHENSIVE DEBUGGING after tests
      - name: Debug - Check everything after tests
        run: |
          echo "=== Current directory contents ==="
          ls -la
          echo "=== Search for ALL possible report directories ==="
          find . -type d $ -name "*report*" -o -name "*results*" $ 2>/dev/null | head -20 || echo "No report directories found"
          echo "=== Search for HTML files ==="
          find . -name "*.html" 2>/dev/null | head -10 || echo "No HTML files found"
          echo "=== playwright-report check ==="
          if [ -d "playwright-report" ]; then
            echo "✅ playwright-report exists!"
            echo "Contents:"
            ls -la playwright-report/
            echo "HTML files in playwright-report:"
            find playwright-report/ -name "*.html" || echo "No HTML files in playwright-report"
          else
            echo "❌ playwright-report does NOT exist"
          fi
          echo "=== Test output files ==="
          if [ -d "test-results" ]; then
            echo "✅ test-results directory exists"
            ls -la test-results/
          else
            echo "❌ No test-results directory"
          fi

      # Upload artifact
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  build-and-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Registry Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Docker Buildx initialisieren
        uses: docker/setup-buildx-action@v3
      - name: Docker-Image erstellen und veröffentlichen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_USER }}/playwright-test-project:latest
          platforms: linux/amd64,linux/arm64
